name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build

  check:
    needs: build
    runs-on: self-hosted
    if: ${{ always() && !success() }}
    steps:
      - name: Fail the pull request
        run: exit 1